Decorating the UserCartRecalculationListener
Sylius/ShopApiPlugin pull request #682
Opened 2020-10-29 14:10 UTC by JakobTolkemit

With this the `UserCartRecalculationListener` listens to `lexik_jwt_authentication.on_jwt_created` instead of `security.interactive_login`, recalculating the cart only on an actual login.

Fixes: https://github.com/Sylius/ShopApiPlugin/issues/667 https://github.com/Sylius/ShopApiPlugin/issues/681

2020-11-04 16:53 UTC, diimpp requested changes

2020-11-04 16:53 UTC, diimpp commented on src/EventListener/UserCartRecalculationListener.php
> +class UserCartRecalculationListener
final

2020-11-04 16:53 UTC, diimpp commented on src/EventListener/UserCartRecalculationListener.php
> +use Sylius\Bundle\CoreBundle\EventListener\UserCartRecalculationListener as CoreListener;
CoreUserCartRecalculationListener

2020-11-04 16:53 UTC, diimpp commented on src/Resources/config/services/listener.xml
> +<container>
I think you need to import this file at `src/Resources/config/services.xml` for it to work

2020-11-04 16:53 UTC, diimpp commented on src/Resources/config/services/listener.xml
> +<container>
Container missing regular `xlmns` definitions

2020-11-04 16:53 UTC, diimpp commented on src/Resources/config/services/listener.xml
> +<container>
If you chose to define new config file, then you need to move existent event listener services over here as well

2020-11-04 16:53 UTC, diimpp commented on src/Resources/config/services/listener.xml
> +                 id="sylius.shop_api_plugin.event_listener.user_cart_recalculation_listener"
Usually `id` should be placed first

2020-11-04 16:53 UTC, diimpp commented on src/Resources/config/services/listener.xml
> +            <tag name="kernel.event_listener" event="lexik_jwt_authentication.on_jwt_created" method="onJwtLogin" />
How about `method="onJwtCreated"` to keep it in line with event name

2020-11-04 16:53 UTC, diimpp commented on src/EventListener/UserCartRecalculationListener.php
> +    private $recalculationListener;
`$decoratedUserCartRecalculationListener`

2020-11-04 16:53 UTC, diimpp commented on src/EventListener/UserCartRecalculationListener.php
> +        $this->recalculationListener->recalculateCartWhileLogin(new UserEvent($user));
This doesn't feel like a proper implementation and overuse of `UserEvent`

2020-11-04 16:53 UTC, diimpp commented on src/EventListener/UserCartRecalculationListener.php
> +    public function recalculateCartWhileLogin(InteractiveLoginEvent $event): void
>     public function recalculateCartWhileLogin(InteractiveLoginEvent $event): void 

`InteractiveLoginEvent $event` doesn't match original `Symfony\Component\EventDispatcher\Event $event` method signature.

Does it even work with `onJwtLogin` supplying `UserEvent` (which does not implement InteractiveLoginEvent) over here?

2020-11-04 16:53 UTC, diimpp commented on src/Resources/config/services/listener.xml
> +            <tag name="kernel.event_listener" event="sylius.user.security.implicit_login" method="recalculateCartWhileLogin" />
Just a question, I don't remember from my testing -- is implicit login works properly with JWT?

2020-11-04 17:02 UTC, diimpp commented
This doesn't solve #667, which prime reason are concurrent frontend calls, not internal over-use of order processing.

As for #681, personally I consider it undesirable side effect and that stateless shop-api shouldn't offer this functionality at all, moreover if a proper stateless cart context would be implemented, then this feature will never be called.

Though for the sake of a bit less broken shop-api plugin it can be done this way for 1.*

2020-11-05 07:29 UTC, JakobTolkemit commented on src/Resources/config/services/listener.xml
> +            <tag name="kernel.event_listener" event="sylius.user.security.implicit_login" method="recalculateCartWhileLogin" />
Apparently it's only dispatched in the `Sylius\Bundle\UserBundle\Security\UserLogin::login` method. This method is only called when a user registers in the ShopBundle.
So, I guess there is no reason to keep it.

2020-11-05 07:35 UTC, JakobTolkemit commented on src/EventListener/UserCartRecalculationListener.php
> +        $this->recalculationListener->recalculateCartWhileLogin(new UserEvent($user));
Really, the whole reason I did this, is because the core listener expects a `Symfony\Component\EventDispatcher\Event` but the JWTCreatedEvent extends the `Symfony\Contracts\EventDispatcher\Event`.
Now I override the class instead, I think there no reason to decorate it.

2020-11-05 08:31 UTC, diimpp requested changes

2020-11-05 08:31 UTC, diimpp commented on src/Resources/config/services/event_listener.xml
> +<container xmlns="http://symfony.com/schema/dic/services">
```xml
<container xmlns="http://symfony.com/schema/dic/services" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://symfony.com/schema/dic/services http://symfony.com/schema/dic/services/services-1.0.xsd">
```

According to sylius xml definitions, it should be like this

2020-11-05 08:31 UTC, diimpp commented on src/Resources/config/services/event_listener.xml
> +    <services>
This file should be named `listeners.xml` according to sylius/sylius naming convention. It a sort of nitpick, but due BC promise, it should be named similar from the start.

2020-11-05 08:31 UTC, diimpp commented on src/Resources/config/services/event_listener.xml
> +    <services>
Missing global public declaration

```
<defaults public="true" />
```

I'm not sure why, but it should be public in accordance with definition for `Sylius\Bundle\CoreBundle\EventListener\UserCartRecalculationListener` and because services that are moved from `services.xml` are public by default and they need to continue to be public due to BC

2020-11-05 08:31 UTC, diimpp commented on src/Resources/config/services/event_listener.xml
> +        <service id="sylius.shop_api_plugin.event_listener.user_registration_listener"
Services `sylius.shop_api_plugin.event_listener.messenger.cart_picked_up_listener` and `sylius.shop_api_plugin.event_listener.messenger.order_completed_listener` should be moved over here as well.

2020-11-05 08:31 UTC, diimpp commented on src/EventListener/UserCartRecalculationListener.php
> +        $this->recalculationListener->recalculateCartWhileLogin(new UserEvent($user));
I agree, override is better

2020-11-05 10:28 UTC, diimpp approved these changes
Thank you, Jakob.

@mamazu @lchrusciel guys, if you agree with the approach, let's not marinate this issue for months :)

2020-11-07 16:41 UTC, lchrusciel commented on src/EventListener/UserCartRecalculationListener.php
> +use Symfony\Contracts\EventDispatcher\Event;
```suggestion
use Symfony\Component\EventDispatcher\Event;
```

Or we should probably add contracts to composer

2020-11-07 16:41 UTC, lchrusciel commented on src/EventListener/UserCartRecalculationListener.php
> +final class UserCartRecalculationListener
Is this class any different from the original implementation?

2020-11-07 16:50 UTC, lchrusciel commented on src/EventListener/UserCartRecalculationListener.php
> +use Symfony\Contracts\EventDispatcher\Event;
Oh, now I see it... https://github.com/Sylius/ShopApiPlugin/pull/682#discussion_r517482564 What would you say for using JWT class explicitly? 

Also, can we maybe make it explicit, that we are removing service from the container (for example in CompilerPass with link to issue on Github) and declare separate service? Or at least link in the comment that is right now, to current issues on Github?

2020-11-09 08:51 UTC, mamazu approved these changes

2020-11-09 09:15 UTC, merged

2020-11-09 09:15 UTC, mamazu commented
Thanks, Jakob! :1st_place_medal: