GitHub actions
Sylius/ShopApiPlugin pull request #691
Opened 2020-12-07 08:48 UTC by clem21

2020-12-08 09:44 UTC, pamil requested changes
The build is failing: https://github.com/clem21/ShopApiPlugin/actions

2020-12-08 16:19 UTC, lchrusciel commented
This can be finished after the merge of https://github.com/Sylius/ShopApiPlugin/pull/688 and release of 1.2

2020-12-11 09:34 UTC, mamazu requested changes

2020-12-11 09:34 UTC, mamazu commented on .github/workflows/build.yml
> +<<<<<<< HEAD
You seem to commit a merge conflict.

2020-12-11 09:34 UTC, mamazu commented on tests/Controller/Cart/SummarizeApiTest.php
> +        $this->client->request('GET', '/shop-api/carts/' . $token, [], [], self::CONTENT_TYPE_HEADER);
Why did that change? Didn't that work before?

2021-02-17 15:05 UTC, merged

2021-02-17 15:05 UTC, lchrusciel commented
Thanks, Clemence! 🎉